# Reprospective Host Agent 設定ファイル（サンプル）
# このファイルを config.yaml にコピーして使用してください

# データベース設定
database:
  type: sqlite  # sqlite または postgresql
  sqlite:
    path: data/host_agent.db  # SQLiteデータベースファイルのパス（相対パスはhost-agent/からの相対）

# デスクトップアクティビティ監視設定
desktop_monitor:
  enabled: true
  monitor_interval: 10  # 監視間隔（秒）

# ファイルシステム監視設定
filesystem_watcher:
  enabled: true

  # 監視対象ディレクトリ（明示的に指定）
  monitored_directories:
    - /home/user/work
    - /home/user/Documents

  # シンボリックリンクの扱い
  symlinks:
    follow: false  # シンボリックリンクを追跡しない（推奨）

  # 除外パターン（正規表現）
  exclude_patterns:
    - ".*\\.tmp$"
    - ".*\\.swp$"
    - ".*~$"
    - ".*/node_modules/.*"
    - ".*/__pycache__/.*"
    - ".*/\\.git/.*"
    - ".*/\\.venv/.*"
    - ".*/venv/.*"
    - ".*/build/.*"
    - ".*/dist/.*"
    - ".*/target/.*"
    - ".*\\.log$"

  # バッファ設定
  buffer:
    max_events: 100      # バッファ最大イベント数
    flush_interval: 10   # フラッシュ間隔（秒）

# ログ設定
logging:
  level: INFO  # DEBUG, INFO, WARNING, ERROR
  format: "[%(asctime)s] [%(levelname)s] [%(name)s] %(message)s"
  # ファイル出力（将来的に実装）
  # file:
  #   enabled: false
  #   path: logs/host_agent.log
